### ISSUE TITLE
Get `PHP Fatal error:  Uncaught exception`

### ISSUE THREAD

**Issue by mostafasoufi** [roots/bedrock#258]
Hello,
After resolve this issue (#257) I get the following error:

```
PHP Fatal error:  Uncaught exception 'Dotenv\Exception\ValidationException' with message 'One or more environment variables failed assertions: WP_SITEURL is missing.' in /var/www/vendor/vlucas/phpdotenv/src/Validator.php:122
Stack trace:
#0 /var/www/vendor/vlucas/phpdotenv/src/Validator.php(47): Dotenv\Validator->assertCallback(Object(Closure), 'is missing')
#1 /var/www/vendor/vlucas/phpdotenv/src/Dotenv.php(93): Dotenv\Validator->__construct(Array, Object(Dotenv\Loader))
#2 /var/www/config/application.php(20): Dotenv\Dotenv->required(Array)
#3 /var/www/web/wp-config.php(8): require_once('/var/www/config...')
#4 /var/www/web/wp/wp-load.php(42): require_once('/var/www/web/wp...')
#5 /var/www/web/wp/wp-blog-header.php(13): require_once('/var/www/web/wp...')
#6 /var/www/web/index.php(5): require('/var/www/web/wp...')
#7 {main}
  thrown in /var/www/vendor/vlucas/phpdotenv/src/Validator.php on line 122

```

**Comment by mostafasoufi** [comment]
Sorry. resolved!

**Comment by retlehs** [comment]
couple things:

1. this is not the place for personal support. use https://discourse.roots.io/
2. saying 'resolved' without explaining what you did to fix your issue isn't helpful for others that might come across this

**Comment by LucasNevesAraujo** [comment]
I'm not using Bedrock but I got the same `Undefined index: SERVER_PROTOCOL` error from #257 by running a CLI command (e.g. `php custom-cli-file.php`) using a wrong database name. Maybe this can help.
